### PR TITLE
added void linux

### PR DESCRIPTION
**Pull request by edward-shen**
Due to the style requiring everything to be white, having "void" in the icon itself looks terrible.

This thus uses the stringless logo instead.

### CODE REVIEW

**Comment by lukechilds** [comment]
Thanks looks great! Looks like it's solid white though, can you tweak the transparency?

> Please make sure the image is a 256x256 solid white png at 75% transparency.

**Comment by alberdingk-thijm** [comment]
Grabbed @edward-shen's version, dropped it into GIMP and tweaked the transparency myself:
os_void
Can't really see it against the white Github background but here is the link: https://user-images.githubusercontent.com/10522804/35822476-65d6a244-0a7a-11e8-80b5-82f4ee112b73.png

**Comment by edward-shen** [comment]
Oh, thanks. Got caught up in schoolwork, so I forgot about this PR. My bad. I'll add your files now.

**Comment by lukechilds** [comment]
Thanks guys but it still appears to be solid white. It needs to be set to 75% transparency, then exported.

**Comment by alberdingk-thijm** [comment]
Fixed it now and put it in another PR #21 (seemed easiest).

**Pull request closed without merging**
