### PR TITLE
Add OpenBSD and Windows 10 os icons

### PR DESCRIPTION
**Pull request by arclabch**

### CODE REVIEW

**Comment by lukechilds** [comment]
@arclabch Thanks for these 👍 

They appear to have some artefacts around the edges though, if you view the images on a white background you can see a slight outline:

https://raw.githubusercontent.com/lukechilds/refind-ambience/56f88e635231e441d9e98e5654c0887bc3f5fc2c/icons/os_openbsd.png

https://raw.githubusercontent.com/lukechilds/refind-ambience/56f88e635231e441d9e98e5654c0887bc3f5fc2c/icons/os_win10.png

If you can clean that up It all looks good to be merged 🙂

**Comment by arclabch** [comment]
You're right. I don't know what happened. I had troubles with the sizes first, then this. Argh. :-) I'll give it another shot.

**Comment by mokeev1995** [comment]
@arclabch any progress here?)

**Comment by lukechilds** [comment]
Closed via https://github.com/lukechilds/refind-ambience/pull/23

**Pull request closed without merging**
