### PR TITLE
Added Linux Mint icon

### PR DESCRIPTION
**Pull request by SnailShea**
Using Linux Mint and getting stuck with the default Linux icon, figured I might help out.

### CODE REVIEW

**Comment by lukechilds** [comment]
Thanks for taking the time to contribute 👍

Would you mind just reducing the size of the icon a bit? The png is fine at 256x256 but if you could reduce the actual mint logo a bit so it's more consistent with the other icons this would be perfect. In my mock up 164x143 seems to work well with the others.

**Comment by SnailShea** [comment]
Absolutely will do! Made the mistake of submitting the pull request before testing the icon. Also labelling my partitions has been kinda wonky so I've had to rename os_linuxmint.png to os_linux.png in my setup to get it to register. Tried resizing per readme after realizing how stupidly massive it is to 132x132 at the center but that's too small. I'll give the 164x143 a shot.

**Comment by lukechilds** [comment]
Great, thanks.

Btw, not sure if you're aware but if rEFInd isn't correctly detecting your volume as a Mint installation you can add a `.VolumeIcon.png` file to the root of your Mint volume and it should use that instead instead of the default linux icon.

Basically the same result as renaming `os_linuxmint.png` to `os_linux.png` like you already have but just a bit cleaner.

**Comment by SnailShea** [comment]
I had no idea, thanks for the heads up! Scaled the icon down a bit, rebooted to test and it looks much more uniform now.

**Comment by lukechilds** [comment]
Awesome, thanks for this!

**Comment by lukechilds** [comment]
Oh also, this may help you get your OS detection issue sorted out: http://www.rodsbooks.com/refind/configfile.html#icons

**Comment by SnailShea** [comment]
You're a life saver! I'll take a look

**Pull request merged**
