### PR TITLE
Better windows 8+ logo

### PR DESCRIPTION
**Pull request by vgf89**
Replacing the weird square win8 logo with a real win8 logo

### CODE REVIEW

**Comment by vgf89** [comment]
Whoops, didn't mean to put both of those commits on my master branch... still figuring out this pull request thing
EDIT: I'll put the tux logo in a separate pull request

**Comment by lukechilds** [comment]
That weird logo was one I made because I'm not keen on the official logo 😉

I'd like to keep my custom logo, but it would probably be a good idea to add the official Windows 8 one too. How about adding the official logo as `os_win8_official.png`?

**Comment by vgf89** [comment]
Fair enough. I'll rename the official one then

**Comment by lukechilds** [comment]
Perfect, thanks 👌

**Pull request merged**
